### ISSUE TITLE
Calorie data not pulling under Activities

### ISSUE THREAD

**Issue by deslni01** [thomaschampagne/elevate#1067]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

Checked both - no luck

### Step 2: Describe your environment

  * Plugin version: 6.16.6 Stable
  * Chrome/Opera/Chromium version: Chrome 91.0.4472.164
  * OS version: Win 10
  
### Step 3: Describe the problem:

Looking at activity history, it looks as if Elevate stopped pulling the calorie/total work data from Strava. Prior to July 9th, calories were shown under activities, but on and after July 9th there was no data being pulled. Showing the activity on Strava from Elevate would pull up the Strava activity page with the calorie data available - seems to just not be pulled anymore.

I tried doing the clear and re-sync option, and now none of the activities have calorie data showing under the Activities page. 

A restart and another attempted clear and re-sync still isn't pulling the calorie data.

**Comment by Jiiwee2** [comment]
Exactly the same issue here. No more calories since Jul 9th.

**Comment by MarekLu** [comment]
I can confirm this behaviour. It started approximately on July 8, 2021. 

I tried to resync all my Strava activities today and numbers in calories column disappeared also from the older rows (calories column is completely empty now).

**Comment by LukeYul** [comment]
Same here.

**Comment by Butter-buns** [comment]
Same issue over here. Thanks!

**Comment by jBeezie** [comment]
Yup yup, been looking at why from Strava to re-sync as well, same issue for me too - no calories. After syncing as someone else mentioned, now no cal data on all old activities either. [2020 Lenovo Thinkpad Chromebook (all updated)] I love the app, it will not stop me from using it just frustrating not to see this data.

**Comment by RaphaelMeudec** [comment]
@thomaschampagne  I looked a bit into this as I faced the same problem. It seems the reason is that the data retrieved at `/athlete/training_activities` by the `activity-synchronize` no longer have the `calories` exposed, which results in post early-July activities to have a `nan` value for calories. This is consistant with MarekLu's comment that calories would disappear from previous activities if trying to clear & synchronize again.

I'm unsure if the calories were exposed at this url before, but the `rawPage` from spec contains it which makes me think it was.

Unfortunately, I see no option for now on how to retrieve the calories info (apart from asking the user token and follow the /api)
