### ISSUE TITLE
Feature request: use Power or Running FTP instead of HR for stress score

### ISSUE THREAD

**Issue by MrAcid** [thomaschampagne/elevate#736]
Currently, Elevate prioritizes HR stress score (HRSS) over the (Cycling) Power Stress Score (PSS) or the Running Stress Score (RSS). I would like to use the PSS and RSS instead of the HR based-score, as I think it is more accurate and thus better reflects actual load as input to my Fitness and Fatigue scores.

The request would be to make this configurable somewhere.

**Comment by ndaman** [comment]
My watch reports a heart rate for my swims now (even though it turns off the hrm while in swim mode), and this absolutely ruins the swim stress score for me, would love to see something like this implemented.

**Comment by stefcameron** [comment]
+1 to what @MrAcid is requesting, though to me, it seems more like a bug to fix than a feature request in light of having a "use RSS toggle" turned-on, and yet I still see this type of calculation for all my runs: `60 HRSS  &  88 RSS   ➔  60 Stress score`

Why is HRSS still being used with the "Enable estimated RSS" toggle "on" (which states that the Fitness Trend will use RSS in that case)?

(Incidentally, I also record run power, but I guess that's not supported yet; not sure if that's because Strava ignores it from the Garmin file, and so Elevate doesn't get it, or if it's an Elevate thing. Still, I'd rather use RSS over HRSS since I feel RSS is more accurate overall.)
