### ISSUE TITLE
Year progression blank :(

### ISSUE THREAD

**Issue by laurahicks30** [thomaschampagne/elevate#784]
Hi 
I am on the latest version and my Year Progressions graph is completely blank :(
Ani ideas.
P.s. thanks for an AWESOME plugn and all the work you do on it!

**Comment by thomaschampagne** [comment]
Please link me a backup of your history ;)

**Comment by PetTerrGit** [comment]
I am facing the same issue. 

- I am on 6.10.1 Stable. Though I have had this issue in earlier versions as well. 
- I am using Chrome Version 72.0.3626.121 (64 bit) on Win 10


- I resync my activities and check year progression. The graphs are blank but markers appear as I scroll over the plot.

I found the following error from my console:

`main.de68831ce07c193c85a6.js:1 ERROR TypeError: Cannot read property 'progressions' of undefined
    at 6.37fb1a0951a979e00de0.js:1
    at Ie (main.de68831ce07c193c85a6.js:1)
    at Function.La (main.de68831ce07c193c85a6.js:1)
    at l.findProgressionsAtDay (6.37fb1a0951a979e00de0.js:1)
    at l.updateData (6.37fb1a0951a979e00de0.js:1)
    at l.ngOnInit (6.37fb1a0951a979e00de0.js:1)
    at main.de68831ce07c193c85a6.js:1
    at main.de68831ce07c193c85a6.js:1
    at To (main.de68831ce07c193c85a6.js:1)
    at $o (main.de68831ce07c193c85a6.js:1)`


My back up is [here](https://www.dropbox.com/s/2ckczksk3vsmtbd/2019.3.13-11.43_v6.10.1.history.json?dl=0)

**Comment by thomaschampagne** [comment]
@laurahicks30 @PetTerrGit I may fixed the problem with this test build:  [v6.10.2_stable_2019-03-16-17-42.zip](https://github.com/thomaschampagne/elevate/files/2974094/v6.10.2_stable_2019-03-16-17-42.zip)

Could you try it and tell me if the problem is fixed?

To install this build follow: https://github.com/thomaschampagne/elevate/wiki/How-to-install-elevate-build-archive
