### ISSUE TITLE
Error during Synchronisation

### ISSUE THREAD

**Issue by MCO7** [thomaschampagne/elevate#785]
* Plugin version: 6.10.1
  * Chrome/Opera/Chromium version: Chrome
  * OS version: W7
  
### Step 3: Describe the problem:
No matter how long I wait, it will not sync ("Please continue your synchronisation in 4-5 hourns..."). The error seems to occur every time at the same "moment". Please find the error log export in attachment.

Please continue your synchronization in 4~5 hours: you have reached the quota of activities which can be synced at the moment. Of course already synced activities will not be re-synced on next sync.

This limit is intended to avoid Strava servers errors or potential overload.
Total activities found 974
Total activities processed 140
Extension local storage occupation: 0.4MB
[syncLogError.log](https://github.com/thomaschampagne/elevate/files/2925688/syncLogError.log)

**Comment by ikr1966** [comment]
I'm having a similar issue and its taken me so far 2 days to get 1300 activities synched out of 2516...

Please continue your synchronization in 4~5 hours: you have reached the quota of activities which can be synced at the moment. Of course already synced activities will not be re-synced on next sync.

This limit is intended to avoid Strava servers errors or potential overload.
Total activities found 2516
Total activities processed 1300
Extension local storage occupation: 3.9MB

**Comment by biff52** [comment]
same issue here, tried to resync, no way. stuck

**Comment by thomaschampagne** [comment]
You have to be really patient with this... I know... I'm working on something new to enable a new way to sync activities. Months of work expected.

**Comment by biff52** [comment]
ok, thx Thomas, good luck.
is it related to the video of TriathlonTaren, and many new users ?

**Comment by thomaschampagne** [comment]
Nope. It comes from technical limitations implement by Strava. https://twitter.com/champagnethomas/status/1095743506193305600

**Comment by thomaschampagne** [comment]
TriathlonTaren is someone recognized in triathlon community?

**Comment by biff52** [comment]
Yes, 
Well, he has a Triathlon YouTube Channel and many followers.
He did a video on Elevate as a substitution of TrainingPeaks.
https://www.youtube.com/channel/UC1AKDrz2GvLxD29W9tow66g

**Comment by biff52** [comment]
He's certified IM coach and does pretty good analysis on many aspects of triathlon.

**Comment by MCO7** [comment]
Thanks Thomas for all your incredible work !
I just worried because my sync activity count don’t increment no matter I try to sync. 
I’m just impatient, I would not have had to do a full resync

**Comment by Vendeen-tri** [comment]
good evening
I am also worried because despite my expectations and my multiple tests my number of activities do not exceed 540.

**Comment by thomaschampagne** [comment]
I have more than 540 activities on my account. Basically you can sync ~400 activities each time. So to sync 1200 activities:

Sync 400 activities →  **wait 5h**  → Continue Sync 400 activities →  **wait 5h**  → Continue Sync 400 activities

**Comment by MCO7** [comment]
So I think that I have another issue than the the Strava limitation with my sync... :-(
I’m trying to synchronize since 2 weeks.

**Comment by biff52** [comment]
I have the same issue as MC07.
My sync gets stuck after 140 activities.
Even I I wait 2 day, it shows the same message and don’t sync more activities.

**Comment by thomaschampagne** [comment]
Ok :/ 

I will ask something that i shouldn't ask... And you normally have to answer NO to the below question:

After changing your password to a temporary one, could provide me your strava credentials by email? So i can sync on my side and fix the error. 

My email: th.champagne[at]gmail.com

Thanks

**Comment by ndechant1** [comment]
Thomas:
I'm preparing to send you my info because I've had the same sync lock problem for days at 53%.  Even about 90 mins ago.  I'm "re-syncing" and for the first time it is still working at 90%!!   You must have fixed something this am.  Only 120 more activities to go!   I'm happy to send my log in if it doesn't work.   My fingers are crossed...

**Comment by vbino** [comment]
I have the same issue. New install due to changing PC's has been stuck at 0 of 156 activities sync'd. I've been trying for a few days to get it going.

_"Please continue your synchronization in 4~5 hours: you have reached the quota of activities which can be synced at the moment. Of course already synced activities will not be re-synced on next sync.

This limit is intended to avoid Strava servers errors or potential overload.
Total activities found 156
Total activities processed 0
Extension local storage occupation: 0.0MB"_

**Comment by biff52** [comment]
it might be possible the issue is caused by a corrupted activity on strava:
https://www.strava.com/activities/1751622158

I can't access anymore to the activity. Either from strava website or mobile app.
 
![image](https://user-images.githubusercontent.com/48329935/54054140-ac92d480-41e9-11e9-9e7b-ca916dbb57f4.png)

**Comment by vbino** [comment]
All of my most recent rides have been 'virtual' on a turbo trainer. The weather in my location has been too poor to get outside :-(

I've done a couple of virtual rides since I had the problem, but the import is always getting stuck importing my most recent ride.

Are Virtual/Corrupt rides causing it?

**Comment by Vendeen-tri** [comment]
The import does not advance at home either for 1 month I am stuck at 540 while I have a little more than 1627 activities. And the number increases :)

**Comment by Vendeen-tri** [comment]
> D'accord :/
> 
> Je vais demander quelque chose que je ne devrais pas demander ... Et vous devez normalement répondre NON à la question ci-dessous:
> 
> Après avoir changé votre mot de passe pour un mot de passe temporaire, pourriez-vous me fournir vos identifiants strava par courrier électronique? Je peux donc synchroniser de mon côté et corriger l'erreur.
> 
> Mon email: th.champagne [at] gmail.com
> 
> Merci

MP

**Comment by chalfontchubby** [comment]
Yep - plus one. Always stops at the same point close to the end of 1175 activities - uninstalled elevate etc. Different PC at different locations.
Do you have the info you need to debug?  Happy to help out as best I can.

**Comment by biff52** [comment]
I could delete the corrupted activity on strava (my activities), and now the sync goes further.

**Comment by StevenC44** [comment]
Hi

I've been trying for a month now.  It gets to 40 activities then the same message as everyone else.  Wait for 4 to 5 hours etc.  I leave it for a day or so.  Sometimes it keeps the forty and kicks out saying wait four-five hours other times it resets to zero then uploads to 40 and stops again.  Any help appreciated.  It looks really good.  Found it on Triathlon Taren. :)

Thanks.

Steven

**Comment by thomaschampagne** [comment]
So i may have fixed some sync errors with this test build: [v6.10.1_stable_2019-03-16-12-00.zip](https://github.com/thomaschampagne/elevate/files/2973800/v6.10.1_stable_2019-03-16-12-00.zip)

I need your help for testing!  In order to install and validate the fix, please follow below steps:

1 - First install the upper given test build in your chrome using this guide: https://github.com/thomaschampagne/elevate/wiki/How-to-install-elevate-build-archive

2 - Start a full sync. The sync window will stay open at the end so you can grab errors in console if needed.

3 - _If the sync is OK (including consistent data checking), you can skip this step and tell me it's OK_. 

Else on the sync window display the developer console like this:
- Press F12
- Click on "Console" tab
- Right click in the logs, then "Save as..."

Drop me the file in that ticket (no sensitive data) or send me it on my email if you previously sent me your credentials (so i can link account with log files)

Hope this helps!

**Comment by StevenC44** [comment]
400 done.  Great!  Will wait the five hours for the next 400.  So much better than 40 then back to zero!

Thanks.

Steven
________________________________

**Comment by vbino** [comment]
The import is working now and all my rides have been sync'd :-)

However the fitness trend graph isn't plotting, nor are the 'Display elevate extended stats' and Analysis in Strava.

**Comment by thomaschampagne** [comment]
@vbino 
>However the fitness trend graph isn't plotting, 

What is "not plotting"? Do you have a backup?

>Display elevate extended stats' and Analysis in Strava.

You may reached the quota. It will come back in few hours

**Comment by vbino** [comment]
> You may reached the quota. It will come back in few hours

I don't think so. I've only logged ~150 activities.

> What is "not plotting"? Do you have a backup?

No backup, this is a fresh install on a new PC. The fitness trend graph is flat. Eg. Stress score is being displayed as zero for all runs/rides. My FTP/HRzones etc have been set in athlete settings but I think it could be something I'm doing? However the 'Display elevate extended stats' button in a Strava workout should work?

**Comment by thomaschampagne** [comment]
@vbino I need more info.... a exported backup of this sync, screenshots, console logs. Else i can't solve

Did you get a HTTP 429 Too many request on strava activities? (F12 => network tab)

(Flat FT is often due to missing FTP, RFTP, SFTP)
