### ISSUE TITLE
Estimated Stress on Manual Activities (specifically running)

### ISSUE THREAD

**Issue by tobiasbunyan** [thomaschampagne/elevate#788]
If running stress is estimated using GAP and moving time, it could be estimated from manual running activities using the pace and time?  Less accurate but better than the half marathon sized hole I now have in my Fitness Trend!

**Comment by tobiasbunyan** [comment]
If anyone points me in the general direction of the appropriate files I might find the time to be able to do this myself ....

**Comment by zeair** [comment]
My garmin failed on Sunday - had to add manual ride - i'm missing HR data - can I somehow add extimated TSS to not break my progress trend?

**Comment by ericwclymer** [comment]
@tobiasbunyan There is lots of context here that might be interesting: https://github.com/thomaschampagne/elevate/issues/733
https://github.com/thomaschampagne/elevate/pull/751

This was all working for a bit, and I'm not sure if it stopped working due to https://twitter.com/champagnethomas/status/1095820968394670086 or something else, but it's stopped working for me recently. 

@thomaschampagne might know more.

**Comment by MarkLutterman** [comment]
Has anything happened on this issue?  I see references above to attempts to allow entry of RSS manually entered run activities, but I'm not sure how I would go about patching into my elevate extensions Version 6.11.1, Released on 2019-04-16.
