### ISSUE TITLE
Quota limits make synchronization impractical

### ISSUE THREAD

**Issue by charleswolf** [thomaschampagne/elevate#794]
I have over 3500 activities in Strava.  Currently it appears that I can only synchronize 400 activities before I reach the quota and have to wait 4-5 hours.  I will have to come back and start the synchronization process about 9 times which is going to take several days.  Due other life commitments I can't come back every 5 hours and press the sync button so realistically it is going to take me 4-9 days before all my activities are synchronized.  The problem with this is I can't use many of the features of this app until the synchronization is complete.  To be clear: the issue isn't the amount of time it takes for all my data to be synchronized, it's that the app isn't usable until all the data is synchronized.   

I have two ideas on how to possibly mitigate this issue:
1) Allow the app to work with a partial synchronization and update each time new activities are added
2) Allow the user to specify a date to start synchronization (prior activities would be ignored)

**Comment by charleswolf** [comment]
I was able to transfer my data by downloading it from my old computer and uploading it on my new.  still a bit of a pain for a new user that hasn't ever synchronized and has several years worth of activity data.

**Comment by thomaschampagne** [comment]
@charleswolf I'm pretty aware that's impractical for users having a large history. Last strava servers changes have been painfull for this project. Your ideas could be implemented.

BTW I'm currently working hard underwater to provide a "new product" based on same UI and data computation to overcome this problem. You will be also able to import data from others sources than Strava.

**Comment by kleinen12** [comment]
Thanks for you hard work\effort Thomas.  This is great tool and it seems to have it challenges for sure.  I look forward to your next releases.

**Comment by myros22** [comment]
I also feel that for people with a lot of activities having a time range selection option for sync activities would help a lot. For fitness trend I might only be interested in the last year worth of activities instead of having to sync all of them.

Thanks for all your work on this extension, it works great and provides tons of useful information

**Comment by BertP** [comment]
Range selection option would be great. Have to sync 2000+ activities on my new Laptop beginning in 2006 (still without success), but I need only the Fitnesstrend for a period of 6 - 12 month.

Thanks for your great work!

**Comment by RonanLB** [comment]
Hello! I'm just hitting the quota issue currently because of some data loss
I synced everything previously and incremental updated kept up, but somehow, everything disappeared, and now that I have to sync everything again I have this daunting warning.
I mean... I'm checking elevate and look forward to have my stats right away :) damn impatient people....
So two suggestions:
- why blocking the features util all activities are synced, would it be possible to download from the most recent to the oldest ones and still be able to provide information for the covered period?
- would a cloud storage option such as dropbox help overcoming those data losses?

I'd be interested in knowing why all the data got cleared up (browser update?, os? etc... is there a way to recover the files that were previously downloaded?)

**Comment by thomaschampagne** [comment]
Unfortunatly i can't fix this problem easily. This problem triggered (between others) the new desktop app project to overcome that constraint. Please read https://blog.usejournal.com/elevate-for-strava-is-jumping-the-strava-fence-to-become-an-independent-desktop-training-app-1f644c2af824

>why blocking the features util all activities are synced, would it be possible to download from the most recent to the oldest ones and still be able to provide information for the covered period

Please create an issue on this. This is indeed an alternative/short term workaround which can be implemented
