### ISSUE TITLE
Activities gone all of a sudden

### ISSUE THREAD

**Issue by ejpho** [thomaschampagne/elevate#830]
Plugin version: 6.11.1 Stable
Angular Core version: 7.2.13
Angular Material version: 7.3.7
D3js version: 5.9.2_
Chrome: 74.0.3729.131 

Very often I loose almost all my older activities in the app.
This happens quite a lot; maybe several times a month.
E.g. Yesterday I made a complete sync of all strava activities after changing some athlete settings. Everything was fine after this sync, but now only the last 60 activities are there. Rest is gone. 
Again... this happens a lot.

I don't use any tools to clean up browser stuff, temp files or whatever.

**Comment by ypgoy** [comment]
This happens to me as well. I think there is a relation with the time that has passed since the last visit to the elevate app. I you open it frequently (like multiple times per week) then there is no issue. When the app isn't opened for a couple of weeks only the last 60 days or so are present. All starting at 0.
Resyncing is cumbersome due to the Strava limitations and takes multiple days of restarting the sync. (I have ~2800 strava activities).

**Comment by KalleBaah** [comment]
Same for me, as described above.

Plugin version: 6.12.0 Stable
Angular Core version: 7.2.15
Angular Material version: 7.3.7
D3js version: 5.9.2
Chrome Version 74.0.3729.157
