### ISSUE TITLE
All data lost after restoring backup then syncing

### ISSUE THREAD

**Issue by Mega-2000** [thomaschampagne/elevate#896]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.14.0
  * Chrome/Opera/Chromium version: Chromium 78.0.3904.97
  * OS version: Manjaro Linux
  
#### Steps to reproduce:

  1. Restore backup
  2. Sync recent activity
  
#### Actual Behavior:

  * What happened? only last activity at screen
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:
After restore :
![image](https://user-images.githubusercontent.com/58372892/69905550-5e47e600-13b5-11ea-859d-bb9360821da5.png)

After sync :
![image](https://user-images.githubusercontent.com/58372892/69905576-baab0580-13b5-11ea-85ae-6de1609fa5b0.png)

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here. 
[2019.11.22-22.28_v6.14.0.history.zip](https://github.com/thomaschampagne/elevate/files/3907491/2019.11.22-22.28_v6.14.0.history.zip)

**Comment by Felipowisky** [comment]
I've experienced this same problem sometime on 2019 (around 2019/04 would be my guess, looking at my backed-up elevate files data) and now (2020/01/20) again.  The first time I got this error, I had no backup and it took weeks to get all Strava data back on Elevate. This week, I hadn't synced Elevate since the end of the year (~2019/12/30, I guess). The first time it synced (no button presses, just had Strava and Elevate opened on separate tabs) it got just the 20 most recent activities, throwing away the 1867+ activities already synced. I have used my most recent backup (from 2019/12/20) to restore and try again, and got the same result: I end up with just the 20 most recent activities from Strava on elevate. I've tried restoring older backups. Same result. Any suggestion to avoid the week long re-sync of all activities?

**Comment by johanverhoeven** [comment]
Same for me too, happened a few times now. Takes ages to resync again.

**Comment by sup3rfly** [comment]
Question:
I'm trying for some time now to get this thing working and with no success. 
I started syncing this morning (8+ hrs ago) and it's at this stage: 1360/2222 activities found. Any ideas how to move this forward?

![image](https://user-images.githubusercontent.com/7603392/75179555-ffd79d00-5742-11ea-8541-6e6763381cf6.png)

It would've been great if there was some kind of pagination and sync the newest to the older, e.g. maybe I don't need data from 2 yrs ago right now. Oddly, I think I am following the right steps.

Appreciate any help,
Alex
