### ISSUE TITLE
Loss of database.

### ISSUE THREAD

**Issue by roccolord** [thomaschampagne/elevate#902]
Please see again, I can't reopen: https://github.com/thomaschampagne/elevate/issues/879

I have backup before and after loss.

**Comment by thomaschampagne** [comment]
Could you provide it? Do you have multiple strava users using same browser?

**Comment by roccolord** [comment]
Hi I'm able to provide it. I use one Strava user only.

Copying the files from my Local Extensions Settings backup to the correct directory and starting Chrome and wait for sync reproduces the problem. The db file looks to be of a greater size then before but all data is list in the interface except to newly synced events.

Is the files in Local Extensions Settings enough or do you need more files? Do you need my Strava credentials? Do you have a place where I can upload the files needed?

**Comment by VincentJGeisler** [comment]
Im having the same problem. suddenly lost old activities. i can load the backup, but as soon as i sync again the old entries are lost.

**Comment by roccolord** [comment]
@thomaschampagne did you have a place where I can upload, and what I shall upload?

**Comment by thomaschampagne** [comment]
I need a backup of your elevate history.

You can upload here or use wetransfert, mediafire,... and send it to me by mail: th.champagne[at]gmail.com.

I'm aware of the problem, i was never able to reproduce it on my side with my strava account.

Even with your backup i will not be able to reproduce it since i need to be connected to your strava account.

Sync became painfull since Strava server changes (1 year ago). That's why i started this below and i provide less support on the extension
https://blog.usejournal.com/elevate-for-strava-is-jumping-the-strava-fence-to-become-an-independent-desktop-training-app-1f644c2af824
