### ISSUE TITLE
Add TSS Ramp Rate in Fitness Trend or Activities? 

### ISSUE THREAD

**Issue by nyedid** [thomaschampagne/elevate#950]
Would it be possible to add a TSS Ramp Rate calculation on either Fitness Trend or Activities? This would be a very useful metric to identify whether an athlete is adding training stress too quickly (or slowly). 

- An ideal implementation of this feature would include the ability to display TSS Ramp Rate and select the interval in question (week/month)
  - An implementation in Fitness Trend could look like a numerical representation near the Fitness/Fatigue Form display.
  - It could also look like a graphical representation of Ramp Rate in the chart itself, with Ramp Rate added as a field in the chart that could show micro-lines representing daily TSS grouped in blocks as TSS across the given period rises/falls. It could also be done with shading under the lines or another visual method. 
  - An implementation in Activities could simply be additional columns that would be able to show Ramp Rate over the last week, two weeks, and last month, similar to how other metrics can be toggled on and off. 
- The calculation would be either cumulative TSS for the selected period, or avg TSS per day for the selected period. Both would be ideal.  

_I did not find any open or closed issues/requests for this._

**Comment by nyedid** [comment]
Just thinking about this more, I wonder if adding this to the Year Progressions tab could work? TSS might be another Progress Type to add there and then all the selections and graphing could work. The problem is Year to Date is too big a range to look at TSS Ramp Rate in. So I'm back to wondering whether the Fitness Trend is the right place to display this. If Year Progressions were just a Progressions tab overall and the user could configure the interval (year, month, week progressions) then displaying TSS Ramp Rate among other data points would be very useful. Could graph progress in Efficiency Factor, for example-- to show athletes how they're getting more efficient in terms of power at a given heart rate over time.

**Comment by csmith1210** [comment]
Okay so doing a deep dive into TSS Ramp Rate here's what I've found and what I propose for this:

So Elevate's Fitness formula is the Cycling Analytics formula for Long Term Stress (LTS) which is equivalent to TrainingPeaks Chronic Training Load (CTL) [all of these are 42 day weighted averages of stress]. Now, Ramp Rate (RR) is based on a change in CTL for a given period. So to me, this should be just a numerical number near the Fitness/Fatigue/Form display. For instance, here is how [Intervals.icu](https://intervals.icu/) displays this:
![intervals.icu](https://i.imgur.com/cVjxwED.jpg)
And here's how TrainingPeaks displays it:
![TrainingPeaks](https://i.imgur.com/zbZqOCk.png)

So how it seems RR is calculated is basically just the CTL (or Fitness) difference between two dates. This is how TrainingPeaks seems to be doing it; for instance, the "Last 7 days" and "Last 28 days" shows 7 and 28 days prior to today's date with matching differences in CTL for the displayed RR. How Intervals.icu seems to be doing it is averaging CTL for each week (Mon-Sun, instead of Sun-Sat) then subtracting the difference of the averages and displaying the same RR for each day that week.

Personally, I think the TrainingPeaks implementation makes more sense, and seems to more closely follow the original idea of RR based on the exercise science guys' info. How I would implement it in Elevate would be another data line under Fitness/Fatigue/Form (same size/color as the "calculated with ->..." line) that would display "Fitness Ramp Rates: 7d xx. 28dxx. 90d xx. 365d xx."

I've never attempted any extension development with NodeJS or TypeScript, but I could dip my feet in to see about an implementation.

Some resources:
- [Why Ramp Rate is an Important Training Metric](https://www.trainingpeaks.com/blog/why-ramp-rate-is-an-important-training-metric/)
- [Understanding TrainingPeaks Ramp Rate For Better Coaching](https://www.trainingpeaks.com/blog/understanding-trainingpeaks-ramp-rate-for-better-coaching/)
- [CTL Ramp Rates, TSB floors & Loading Patterns by Alan Couzens](https://www.alancouzens.com/blog/CTLramp.html)
- [The CTL Ramp Rate by Joe Friel](https://joefrielsblog.com/the-ctl-ramp-rate/)
- [The training load table is now a chart - Cycling Analystics](https://www.cyclinganalytics.com/blog/2012/06/the-training-load-table-is-now-a-chart)
- [ATL, CTL & TSB explained - Ian Barrington](https://ianbarrington.com/2007/03/02/atl-ctl-tsb-explained/)

**Comment by nyedid** [comment]
@csmith1210 Thanks so much for the thoughtful reply. I saw the linked pull request and the implementation of RR you put in looks perfect. Many many thanks! Can't wait to play with it in the extension with my data!
