### ISSUE TITLE
Add Intensity Factor to Activities List or Fitness Analysis Table

### ISSUE THREAD

**Issue by nyedid** [thomaschampagne/elevate#962]
- Intensity Factor and Chronic Intensity Load are two helpful metrics that some use to train. 
- Intensity Factor is determined Normalized Power (i.e., weighted power in Elevate) divided by FTP. 

Would be great to see this added as an option in the dropdown list in the Activities tab to allow the user to toggle this on as one of the columns displayed. Could also be added as a column in the Fitness Analysis table. 

Also displaying IF would be part of the calculation for CIL described in [this issue](https://github.com/thomaschampagne/elevate/issues/936).

**Comment by csmith1210** [comment]
This is actually simple for the Activities page; it was already added in but commented out and never fully finished. You can also already see this metric by clicking the extended stats button on a Strava activities page. See `line 475` of `plugin/app/src/app/activities/activity-columns.namespace.ts`. To easily fix this, the change would be: 
`new NumberColumn(Category.POWER, "extendedStats.powerData.punchFactor", null, "Intensity", Print.number, 2),`
(as noted in past release notes, Intensity Factor is trademarked by TrainingPeaks)

So that's a relatively simple pull request, but on the issue of the Fitness table - I'm not sure it's the best strategy to start adding columns to this table. Eventually after you start adding all of these columns, then you'd need a selector like the Activities page. 

Now, the CIL is a different addition, though, since it matches the rest of the Fitness page (CTL, ATL, TSB) in my opinion. Although one could argue that Intensity Factor matches the rest of the table and would make sense once CIL is included in Elevate. But for now, I think it would be best to leave that table alone.

Let me know your thoughts, I can submit a pull request if this suits you: [csmith1210/elevate/feature/add-intensity](https://github.com/csmith1210/elevate/tree/feature/add-intensity)

**Comment by nyedid** [comment]
@csmith1210 Ah interesting, I wonder why it was abandoned. Totally understand about not monkeying with the Fitness table. 

Yes, I think adding it to the selection dropdown on the Activities page would be fantastic. Thanks!
