### ISSUE TITLE
Percent rankings on segments are gone

### ISSUE THREAD

**Issue by aiacciu87** [thomaschampagne/elevate#994]
Hello,

For a few days, the ranks in segments no longer displayed (is was like: **##/### #,#%** format).

I disabled all of my other Chrome extensions to see if there was a conflict. I uninstalled and re-installed Elevate App, nothing helps.

**Before:**
![9660d212-1aa9-11e6-8d1a-0045e1d99980](https://user-images.githubusercontent.com/874950/90864856-ba162d00-e391-11ea-8aed-43d4f30ec759.png)

**After:**
![90494384-bf7e3800-e143-11ea-9e19-1393df119458](https://user-images.githubusercontent.com/874950/90864855-b84c6980-e391-11ea-9ff2-1b207402acb6.png)

Any idea? Thanks you!

**Comment by Taaber** [comment]
Strava is limiting API calls. The default rate limit now only allows 100 requests every 15 minutes, with up to 1,000 requests per day https://developers.strava.com/docs/getting-started/. Premium Users are allowed more calls.
Because of this the Feature was disabled since it will make a API call for each entry! But it can be enabled again in the Elevate Global Settings "Enable segment time comparison to KOM/QOM-PR-year PR display-rank column".

![ElavateSettings](https://user-images.githubusercontent.com/26114402/92075949-d070af80-edb9-11ea-8a4b-55fdfb7ce941.png)

But if you enable the feature and are a free user you will hit the limit very fast and will be blocked for 15 Minutes and subsequently a day

**Comment by aiacciu87** [comment]
Perfect. Thank you!
